//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Purchase
{
    using System;
    using System.Collections.Generic;
    
    public partial class accountmain1
    {
        public decimal id { get; set; }
        public Nullable<System.DateTime> dt { get; set; }
        public Nullable<decimal> accountid { get; set; }
        public Nullable<decimal> custid { get; set; }
        public Nullable<decimal> debit { get; set; }
        public Nullable<decimal> credit { get; set; }
        public Nullable<decimal> balance { get; set; }
        public string detail { get; set; }
        public string dealing { get; set; }
        public Nullable<decimal> renum { get; set; }
        public Nullable<decimal> idunique { get; set; }
        public Nullable<bool> active { get; set; }
        public Nullable<bool> isdeleted { get; set; }
        public string ship { get; set; }
        public string en_dealing { get; set; }
        public string deal { get; set; }
        public string Myuser { get; set; }
        public Nullable<bool> IsUser { get; set; }
        public Nullable<decimal> CloseRegnum { get; set; }
        public Nullable<decimal> Cpu { get; set; }
        public string currency { get; set; }
        public Nullable<double> currencyval { get; set; }
        public Nullable<decimal> BranchID { get; set; }
        public Nullable<decimal> CostID { get; set; }
    }
}
