//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Purchase
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class AccountingSystem : DbContext
    {
        public AccountingSystem()
            : base("name=AccountingSystem")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<accountmain> accountmains { get; set; }
        public virtual DbSet<Accounts_Balance> Accounts_Balance { get; set; }
        public virtual DbSet<AreasSet> AreasSets { get; set; }
        public virtual DbSet<BankBranch> BankBranches { get; set; }
        public virtual DbSet<BankSet> BankSets { get; set; }
        public virtual DbSet<Branch> Branches { get; set; }
        public virtual DbSet<CompanyInfo> CompanyInfoes { get; set; }
        public virtual DbSet<CurrencySet> CurrencySets { get; set; }
        public virtual DbSet<debenturedetail> debenturedetails { get; set; }
        public virtual DbSet<debenture> debentures { get; set; }
        public virtual DbSet<Group> Groups { get; set; }
        public virtual DbSet<InvoiceDetail> InvoiceDetails { get; set; }
        public virtual DbSet<Invoice> Invoices { get; set; }
        public virtual DbSet<ItemGroup> ItemGroups { get; set; }
        public virtual DbSet<ItemMeasurementUnit> ItemMeasurementUnits { get; set; }
        public virtual DbSet<Item> Items { get; set; }
        public virtual DbSet<PaymentType> PaymentTypes { get; set; }
        public virtual DbSet<PermissionControl> PermissionControls { get; set; }
        public virtual DbSet<SaleInvoiceDetail> SaleInvoiceDetails { get; set; }
        public virtual DbSet<SalesInvoice> SalesInvoices { get; set; }
        public virtual DbSet<SupplierSet> SupplierSets { get; set; }
        public virtual DbSet<TreeAccount> TreeAccounts { get; set; }
        public virtual DbSet<Tree> Trees { get; set; }
        public virtual DbSet<Trees1> Trees1 { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<VendorSet> VendorSets { get; set; }
        public virtual DbSet<Wharehous> Wharehouses { get; set; }
    }
}
