using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Drawing;
using System.Data;
using System.Text;
using System.Linq;
using System.Threading.Tasks;
using System.Windows.Forms;
using DevExpress.XtraEditors;
using System.Data.Entity;
using System.Threading;

namespace Purchase
{
    public partial class AddUser : DevExpress.XtraEditors.XtraUserControl
    {
        Purchase.AccountingSystem dbContext;
        public AddUser()
        {
            InitializeComponent();
            // This line of code is generated by Data Source Configuration Wizard
            // Instantiate a new DBContext
             dbContext = new Purchase.AccountingSystem();
            // Call the Load method to get the data for the given DbSet from the database.
            dbContext.Groups.Load();
            // This line of code is generated by Data Source Configuration Wizard
            bindingSource1.DataSource = dbContext.Groups.Local.ToBindingList();
            // This line of code is generated by Data Source Configuration Wizard
            // Instantiate a new DBContext
            // Call the Load method to get the data for the given DbSet from the database.
            dbContext.Branches.Load();
            // This line of code is generated by Data Source Configuration Wizard
            bindingSource2.DataSource = dbContext.Branches.Local.ToBindingList();
        }

        private void label1_Click(object sender, EventArgs e)
        {

        }

        private void lookUpEdit1_EditValueChanged(object sender, EventArgs e)
        {

        }

        private void AddUser_Load(object sender, EventArgs e)
        {
            using (var db = new AccountingSystem())
            {
                var dc = from c in db.Users
                         //where c.Id.Equals(InvoiceID)
                         select new
                         {
                             c.Id,
                         };
                var list = dc.ToList();
                int id = list.Count;
                Code.Text = (id + 1).ToString();
            }
            fillsearch();
        }

        private void save_Click(object sender, EventArgs e)
        {
            
            if(search.Text.Equals("") ||search.Text.Equals(" "))
                DevExpress.XtraEditors.XtraMessageBox.Show("الرجاء ادخال اسم المستخدم");
            else if (Branch.Text.Equals("") || Branch.Text.Equals(" "))
                DevExpress.XtraEditors.XtraMessageBox.Show("الرجاء اختيار الفرع");
            else if (Password.Text.Equals("") || Password.Text.Equals(" "))
                DevExpress.XtraEditors.XtraMessageBox.Show("الرجاء ادخال كلمة المرور");
            else
            {
                news.Visible = true;
                save.Visible = false;
                update.Visible = true;
                splashScreenManager1.ShowWaitForm();
                Thread.Sleep(1000);
                using (var db = new AccountingSystem())
                {
                    var User = db.Users.Create();
                    User.UCode = Code.Text;
                    User.UName = search.Text;
                    User.UStatus = Status.Checked.ToString();
                    User.UBranch = Branch.EditValue.ToString();
                    User.UPassword = Password.Text;
                    User.UGroup = Group.EditValue.ToString();
                    db.Users.Add(User);

                    try
                    {
                        db.SaveChanges();
                    }
                    catch (Exception dbEx)
                    {
                        Exception raise = dbEx;
                        var val = dbEx.InnerException;
                        MessageBox.Show(val.ToString());
                    }
                }
                fillsearch();
                splashScreenManager1.CloseWaitForm();
            }
        }

        private void news_Click(object sender, EventArgs e)
        {
            update.Visible = false;
            save.Visible = true;
            using (var db = new AccountingSystem())
            {
                var dc = from c in db.Users
                         //where c.Id.Equals(InvoiceID)
                         select new
                         {
                             c.Id,
                         };
                var list = dc.ToList();
                int id = list.Count;
                Code.Text = (id + 1).ToString();
            }
            search.Text = "";
            Password.Text = "";
            Status.Checked = false;
            
        }

        private void update_Click(object sender, EventArgs e)
        {
            save.Visible = false;
            news.Visible = true;
            update.Visible = true;
            VendorSet Sup = new VendorSet();
            //InitializeComponent();
            splashScreenManager1.ShowWaitForm();
            Thread.Sleep(1000);
            using (var db = new AccountingSystem())
            {
                try
                {

                    var User = db.Users.First(x => x.UCode.Equals(Code.Text));
                    User.UCode = Code.Text;
                    User.UName = search.Text;
                    User.UStatus = Status.Checked.ToString();
                    User.UBranch = Branch.EditValue.ToString();
                    User.UPassword = Password.Text;
                    User.UGroup = Group.Text;
                    
                    db.Entry(User).State = System.Data.Entity.EntityState.Modified;
                    db.SaveChanges();
                }
                catch (System.Data.Entity.Validation.DbEntityValidationException dbEx)
                {
                    Exception raise = dbEx;
                    foreach (var validationErrors in dbEx.EntityValidationErrors)
                    {
                        foreach (var validationError in validationErrors.ValidationErrors)
                        {
                            string message = string.Format("{0}:{1}",
                                validationErrors.Entry.Entity.ToString(),
                                validationError.ErrorMessage);
                            raise = new InvalidOperationException(message, raise);
                        }
                    }
                    throw raise;
                }
                catch (Exception dbEx)
                {
                    Exception raise = dbEx;
                    var val = dbEx.InnerException;
                    MessageBox.Show(val.ToString());
                    //throw raise;
                }
            }
            fillsearch();
            splashScreenManager1.CloseWaitForm();
        }

        private void cancel_Click(object sender, EventArgs e)
        {

        }

        private void simpleButton1_Click(object sender, EventArgs e)
        {
            //AddGroup AG = new AddGroup();
            Form storeForm = new AddGroup();
            //storeForm.Controls.Add(new AddCurrnceys());
            //storeForm.BackColor = System.Drawing.Color.White;
            storeForm.StartPosition = FormStartPosition.CenterScreen;
            //storeForm.Width = 320;
            //storeForm.WindowState = FormWindowState.Maximized;
            DialogResult x = storeForm.ShowDialog();

            if (x == DialogResult.Cancel)
            {
                dbContext = new Purchase.AccountingSystem();
                bindingSource1.DataSource = dbContext.Groups.ToList();
                Group.Refresh();
            }
        }

        private void Group_EditValueChanged(object sender, EventArgs e)
        {
            using (var db = new AccountingSystem())
            {
                var dc = from c in db.PermissionControls
                             where c.CGroupId.Equals(Group.EditValue.ToString())
                             select new
                             {
                                 c.Id,
                                 c.CGroupId,
                                 c.CAdmin,
                                 c.CSells,
                                 c.CBuys,
                                 c.CWarehouse,
                                 c.CVendorSupplier,
                                 c.CAccount,
                                 c.COther
                             };
                    var list = dc.ToList();
                    if (list.Count != 0)
                    {
                        if (list[0].COther)
                            Other.Checked = true;
                        else
                            Other.Checked = false;
                        if (list[0].CAccount)
                            Account.Checked = true;
                        else
                            Account.Checked = false;
                        if (list[0].CAdmin)
                            Admin.Checked = true;
                        else
                            Admin.Checked = false;
                        if (list[0].CSells)
                            Sells.Checked = true;
                        else
                            Sells.Checked = false;
                        if (list[0].CBuys)
                            Buys.Checked = true;
                        else
                            Buys.Checked = false;
                        if (list[0].CWarehouse)
                            Warehouse.Checked = true;
                        else
                            Warehouse.Checked = false;
                        if (list[0].CVendorSupplier)
                            VendorSupplier.Checked = true;
                        else
                            VendorSupplier.Checked = false;
                    }
                    
                
            }
        }

        private void simpleButton2_Click(object sender, EventArgs e)
        {
            Form storeForm = new AddBranch();
            //storeForm.Controls.Add(new AddCurrnceys());
            //storeForm.BackColor = System.Drawing.Color.White;
            storeForm.StartPosition = FormStartPosition.CenterScreen;
            //storeForm.Width = 320;
            //storeForm.WindowState = FormWindowState.Maximized;
            DialogResult x = storeForm.ShowDialog();

            if (x == DialogResult.Cancel)
            {
                dbContext = new Purchase.AccountingSystem();
                bindingSource2.DataSource = dbContext.Branches.ToList();
                Branch.Refresh();
            }
        }
        private List<string> Datos()
        {

            List<string> listDatos = new List<string>();

            using (var db = new AccountingSystem())
            {
                var dc = from c in db.Users
                         //where c.Id.Equals(InvoiceID)
                         select new
                         {
                             c.Id,
                             c.UName
                         };
                var list = dc.ToList();
                for (int i = 0; i < list.Count; i++)
                {
                    listDatos.Add(list[i].UName.ToString());
                }

            }
            return listDatos;
        }
        private void fillsearch()
        {

            List<string> lista = Datos();
            search.AutoCompleteMode = AutoCompleteMode.SuggestAppend;
            AutoCompleteStringCollection data = new AutoCompleteStringCollection();
            data.AddRange(lista.ToArray());
            search.AutoCompleteCustomSource = data;
            search.AutoCompleteSource = AutoCompleteSource.CustomSource;
        }

        private void simpleButton3_Click(object sender, EventArgs e)
        {
            save.Visible = false;
            news.Visible = true;
            update.Visible = true;
            using (var db = new AccountingSystem())
            {
                var dc = from c in db.Users
                         where c.UName.Equals(search.Text)
                         select new
                         {
                             c.UCode,
                             c.UName,
                             c.UStatus,
                             c.UPassword,
                             c.UBranch,
                             c.UGroup,
                         };
                var list = dc.ToList();
                if (list.Count != 0)
                {
                    if (list[0].UStatus.Equals("True"))
                        Status.Checked = true;
                    else
                        Status.Checked = false;
                    Code.Text = list[0].UCode;
                    search.Text = list[0].UName;
                    Password.Text = list[0].UPassword;
                    Branch.Text = list[0].UBranch;
                    Group.Text = list[0].UGroup;
                }
                else
                {
                    MessageBox.Show("عفوا لا يوجد مستخدم بهذا الاسم", "تنبيه", MessageBoxButtons.OK, MessageBoxIcon.Information);
                }
            }
        }
    }
}
