//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Purchase
{
    using System;
    using System.Collections.Generic;
    
    public partial class Branch
    {
        public int Id { get; set; }
        public string BId { get; set; }
        public string BName { get; set; }
        public string BStatus { get; set; }
        public string BPhone1 { get; set; }
        public string BPhone2 { get; set; }
        public string BAddress { get; set; }
    }
}
