//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Purchase
{
    using System;
    using System.Collections.Generic;
    
    public partial class debenturedetail
    {
        public int DebentureID { get; set; }
        public Nullable<int> AccountID { get; set; }
        public Nullable<double> Amount { get; set; }
        public string Notes { get; set; }
        public Nullable<int> ChequeID { get; set; }
        public Nullable<int> Narration { get; set; }
        public Nullable<System.DateTime> ValueDate { get; set; }
        public Nullable<int> Payed { get; set; }
        public Nullable<int> CenterID { get; set; }
        public Nullable<int> GridNo { get; set; }
        public Nullable<int> BranchID { get; set; }
        public int Id { get; set; }
    
        public virtual debenture debenture { get; set; }
        public virtual TreeAccount TreeAccount { get; set; }
    }
}
