using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows.Forms;
using System.Data.Entity;

namespace Purchase
{
    public partial class frmSalesReports : Form
    {
        public frmSalesReports()
        {
            InitializeComponent();
            GetCustomers();
            GetItems();
            // This line of code is generated by Data Source Configuration Wizard
            // Instantiate a new DBContext
            Purchase.AccountingSystem dbContext = new Purchase.AccountingSystem();
            // Call the Load method to get the data for the given DbSet from the database.
            dbContext.VendorSets.Load();
            // This line of code is generated by Data Source Configuration Wizard
            bindingSource1.DataSource = dbContext.VendorSets.Local.ToBindingList();
            // This line of code is generated by Data Source Configuration Wizard
            // Instantiate a new DBContext
            // Call the Load method to get the data for the given DbSet from the database.
            dbContext.Items.Load();
            // This line of code is generated by Data Source Configuration Wizard
            bindingSource2.DataSource = dbContext.Items.Local.ToBindingList();
        }
        private void GetCustomers()
        {
            using (var db = new AccountingSystem())
            {
                var dc = from c in db.VendorSets
                         select new { c.Id, c.VendorName };
                cmbCustomerID.Properties.DataSource = dc.ToList();
                cmbCustomerID.Properties.ValueMember = "Id";
                cmbCustomerID.Properties.DisplayMember = "VendorName";
            }
        }

        private void GetItems()
        {
            using (var db = new AccountingSystem())
            {
                var dc = from c in db.Items
                         select new { c.Id, c.Name };
                cmbItem.Properties.DataSource = dc.ToList();
                cmbItem.Properties.ValueMember = "Id";
                cmbItem.Properties.DisplayMember = "Name";
            }
        }

        private void cmdClose_Click(object sender, EventArgs e)
        {
            base.Dispose();
        }

        private void rdoList_CheckedChanged(object sender, EventArgs e)
        {
            FromDate.Enabled = rdoList.Checked;
            DateTo.Enabled = rdoList.Checked;
        }

        private void rdoItem_CheckedChanged(object sender, EventArgs e)
        {
            cmbItem.Enabled = rdoItem.Checked;
        }

        private void rdoCustomer_CheckedChanged(object sender, EventArgs e)
        {
            cmbCustomerID.Enabled = rdoCustomer.Checked;
        }

        private void frmSalesReports_Load(object sender, EventArgs e)
        {
            RdoInvoice.Checked = true;
        }

        private void RdoInvoice_CheckedChanged(object sender, EventArgs e)
        {
            txtInvoiceNo.Enabled=RdoInvoice.Checked;
        }
    }
}
