//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Purchase
{
    using System;
    using System.Collections.Generic;
    
    public partial class Invoice
    {
        public Invoice()
        {
            this.InvoiceDetails = new HashSet<InvoiceDetail>();
        }
    
        public int InvoiceId { get; set; }
        public System.DateTime InvoiceDate { get; set; }
        public int SupplierId { get; set; }
        public Nullable<double> Total { get; set; }
        public long WorkflowState { get; set; }
        public Nullable<long> cuid { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
        public Nullable<long> duid { get; set; }
        public Nullable<System.DateTime> DeleteTime { get; set; }
        public Nullable<int> State { get; set; }
    
        public virtual ICollection<InvoiceDetail> InvoiceDetails { get; set; }
        public virtual SupplierSet SupplierSet { get; set; }
    }
}
