//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Purchase
{
    using System;
    using System.Collections.Generic;
    
    public partial class ItemMeasurementUnit
    {
        public int Id { get; set; }
        public Nullable<int> ItemId { get; set; }
        public string Barcode { get; set; }
        public Nullable<int> NumOfPieces { get; set; }
        public string Unit { get; set; }
        public Nullable<decimal> SalePrice { get; set; }
        public Nullable<decimal> PurchasePrice { get; set; }
        public Nullable<bool> PurchaseDefault { get; set; }
        public Nullable<bool> SaleDefault { get; set; }
    
        public virtual Item Item { get; set; }
    }
}
