//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Purchase
{
    using System;
    using System.Collections.Generic;
    
    public partial class Item
    {
        public Item()
        {
            this.InvoiceDetails = new HashSet<InvoiceDetail>();
            this.ItemMeasurementUnits = new HashSet<ItemMeasurementUnit>();
        }
    
        public int Id { get; set; }
        public string Code { get; set; }
        public string Name { get; set; }
        public string Type { get; set; }
        public Nullable<bool> Status { get; set; }
        public Nullable<System.DateTime> ExpireDate { get; set; }
        public Nullable<int> ItemGroupsId { get; set; }
        public Nullable<int> WharehouseId { get; set; }
        public Nullable<int> MinQouantity { get; set; }
        public Nullable<int> MonthlySale { get; set; }
        public Nullable<int> FreezDate { get; set; }
        public Nullable<int> ExpireAlarmDays { get; set; }
        public Nullable<int> SupplierId { get; set; }
        public Nullable<int> VendorId { get; set; }
        public string Discription { get; set; }
        public Nullable<bool> HasExpireDate { get; set; }
    
        public virtual ICollection<InvoiceDetail> InvoiceDetails { get; set; }
        public virtual ItemGroup ItemGroup { get; set; }
        public virtual ICollection<ItemMeasurementUnit> ItemMeasurementUnits { get; set; }
        public virtual Wharehous Wharehous { get; set; }
    }
}
