//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Purchase
{
    using System;
    using System.Collections.Generic;
    
    public partial class PermissionControl
    {
        public int Id { get; set; }
        public string CGroupId { get; set; }
        public bool CAdmin { get; set; }
        public bool CSells { get; set; }
        public bool CBuys { get; set; }
        public bool CWarehouse { get; set; }
        public bool CAccount { get; set; }
        public bool CVendorSupplier { get; set; }
        public bool COther { get; set; }
    }
}
