//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Purchase
{
    using System;
    using System.Collections.Generic;
    
    public partial class SaleInvoiceDetail
    {
        public int DetailsId { get; set; }
        public int ItemID { get; set; }
        public double Quantity { get; set; }
        public string Unit { get; set; }
        public double Price { get; set; }
        public int SalesInvoicesId { get; set; }
    
        public virtual SalesInvoice SalesInvoice { get; set; }
    }
}
