//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Purchase
{
    using System;
    using System.Collections.Generic;
    
    public partial class SalesInvoice
    {
        public SalesInvoice()
        {
            this.SaleInvoiceDetails = new HashSet<SaleInvoiceDetail>();
        }
    
        public int Id { get; set; }
        public string InoviceNo { get; set; }
        public System.DateTime InvoiceDate { get; set; }
        public int CustomerID { get; set; }
        public int UserID { get; set; }
        public int CurrencyID { get; set; }
        public double Rate { get; set; }
        public int PaymentType { get; set; }
        public string ChequeNo { get; set; }
        public Nullable<System.DateTime> ChequeDate { get; set; }
        public int Paid { get; set; }
        public double Tax { get; set; }
        public double Discount { get; set; }
        public string Notes { get; set; }
        public Nullable<int> Canceled { get; set; }
    
        public virtual ICollection<SaleInvoiceDetail> SaleInvoiceDetails { get; set; }
    }
}
