using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Drawing;
using System.Data;
using System.Text;
using System.Linq;
using System.Threading.Tasks;
using System.Windows.Forms;
using DevExpress.XtraEditors;
using System.Data.Entity;

namespace Purchase
{
    public partial class SelectAccounts : DevExpress.XtraEditors.XtraUserControl
    {
        public SelectAccounts()
        {
            InitializeComponent();
            // This line of code is generated by Data Source Configuration Wizard
            // Instantiate a new DBContext
            Purchase.AccountingSystem dbContext = new Purchase.AccountingSystem();
            // Call the Load method to get the data for the given DbSet from the database.
            dbContext.TreeAccounts.Load();
            // This line of code is generated by Data Source Configuration Wizard
            // This line of code is generated by Data Source Configuration Wizard
            // Instantiate a new DBContext
            // Call the Load method to get the data for the given DbSet from the database.
            dbContext.TreeAccounts.Load();
            // This line of code is generated by Data Source Configuration Wizard
            bindingSource2.DataSource = dbContext.TreeAccounts.Local.ToBindingList();
        }

        private void treeList1_FocusedNodeChanged(object sender, DevExpress.XtraTreeList.FocusedNodeChangedEventArgs e)
        {
            
            
        }

        private void treeList1_DoubleClick(object sender, EventArgs e)
        {
            String name = treeList1.FocusedNode.GetValue("Name").ToString();
            int id = int.Parse(treeList1.FocusedNode.GetValue("Id").ToString());
            Suppliers sp = new Suppliers();
            sp.SetAccountOne(name,id);
            this.ParentForm.Close();
            
        }
    }
}
