//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Purchase
{
    using System;
    using System.Collections.Generic;
    
    public partial class TreeAccount
    {
        public TreeAccount()
        {
            this.debenturedetails = new HashSet<debenturedetail>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public Nullable<int> levels { get; set; }
        public Nullable<int> parentId { get; set; }
        public Nullable<bool> isparent { get; set; }
        public Nullable<decimal> related { get; set; }
        public string operands { get; set; }
        public Nullable<int> type { get; set; }
        public string sign { get; set; }
        public Nullable<bool> active { get; set; }
        public Nullable<decimal> debit { get; set; }
        public Nullable<decimal> credit { get; set; }
        public Nullable<decimal> balance { get; set; }
        public Nullable<decimal> cmpnum { get; set; }
        public Nullable<System.DateTime> dt { get; set; }
        public string note { get; set; }
        public Nullable<bool> ismoney { get; set; }
        public string tag { get; set; }
        public Nullable<decimal> BranchID { get; set; }
        public string nameEn { get; set; }
        public string typeEn { get; set; }
        public string parentEn { get; set; }
    
        public virtual ICollection<debenturedetail> debenturedetails { get; set; }
    }
}
