using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Drawing;
using System.Data;
using System.Text;
using System.Linq;
using System.Threading.Tasks;
using System.Windows.Forms;
using DevExpress.XtraEditors;
using System.Data.Entity;

namespace Purchase
{
    public partial class UserView : DevExpress.XtraEditors.XtraUserControl
    {
        public UserView()
        {
            InitializeComponent();
            // This line of code is generated by Data Source Configuration Wizard
            // Instantiate a new DBContext
            Purchase.AccountingSystem dbContext = new Purchase.AccountingSystem();
            // Call the Load method to get the data for the given DbSet from the database.
            dbContext.Users.Load();
            // This line of code is generated by Data Source Configuration Wizard
            bindingSource1.DataSource = dbContext.Users.Local.ToBindingList();
        }

        private void simpleButton1_Click(object sender, EventArgs e)
        {
            string FileName = "C:\\Users\\Public\\User.xls";
            gridControl1.ExportToXls(FileName);
        }
    }
}
