//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Purchase
{
    using System;
    using System.Collections.Generic;
    
    public partial class VendorSet
    {
        public int Id { get; set; }
        public string VendorId { get; set; }
        public string VendorName { get; set; }
        public string VendorStartBalance { get; set; }
        public string VendorStartBlnsDate { get; set; }
        public string VendorTypeOfBalance { get; set; }
        public string VendorStatus { get; set; }
        public string VendorBranch { get; set; }
        public string VendorBranchCurrency { get; set; }
        public string VendorLedger { get; set; }
        public string VendorSupplementingAccount { get; set; }
        public string VendorCompanyName { get; set; }
        public string VendorResponsible { get; set; }
        public string VendorArea { get; set; }
        public string VendorAddress { get; set; }
        public string VendorPhone1 { get; set; }
        public string VendorPhone2 { get; set; }
        public string VendorWebsite { get; set; }
        public string VendorEmail { get; set; }
        public string VendorBankNoAccount { get; set; }
        public string VendorBankName { get; set; }
        public string VendorBankBranach { get; set; }
    }
}
