//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Purchase
{
    using System;
    using System.Collections.Generic;
    
    public partial class Wharehous
    {
        public Wharehous()
        {
            this.Items = new HashSet<Item>();
        }
    
        public int Id { get; set; }
        public string StoreName { get; set; }
        public Nullable<int> BranchID { get; set; }
        public Nullable<bool> Status { get; set; }
        public Nullable<decimal> Area { get; set; }
        public string Address { get; set; }
        public string Mobile { get; set; }
        public Nullable<decimal> Size { get; set; }
    
        public virtual ICollection<Item> Items { get; set; }
    }
}
